name: thorfin_ai
description: THORFIN - Juwel's Personal AI Assistant
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  speech_to_text: ^7.5.0
  flutter_tts: ^4.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
